/*
 * Decompiled with CFR 0.152.
 */
package com.hypixel.hytale.protocol;

import com.hypixel.hytale.protocol.Packet;
import com.hypixel.hytale.protocol.io.ValidationResult;
import com.hypixel.hytale.protocol.packets.asseteditor.AssetEditorActivateButton;
import com.hypixel.hytale.protocol.packets.asseteditor.AssetEditorAssetListSetup;
import com.hypixel.hytale.protocol.packets.asseteditor.AssetEditorAssetListUpdate;
import com.hypixel.hytale.protocol.packets.asseteditor.AssetEditorAssetPackSetup;
import com.hypixel.hytale.protocol.packets.asseteditor.AssetEditorAssetUpdated;
import com.hypixel.hytale.protocol.packets.asseteditor.AssetEditorAuthorization;
import com.hypixel.hytale.protocol.packets.asseteditor.AssetEditorCapabilities;
import com.hypixel.hytale.protocol.packets.asseteditor.AssetEditorCreateAsset;
import com.hypixel.hytale.protocol.packets.asseteditor.AssetEditorCreateAssetPack;
import com.hypixel.hytale.protocol.packets.asseteditor.AssetEditorCreateDirectory;
import com.hypixel.hytale.protocol.packets.asseteditor.AssetEditorDeleteAsset;
import com.hypixel.hytale.protocol.packets.asseteditor.AssetEditorDeleteAssetPack;
import com.hypixel.hytale.protocol.packets.asseteditor.AssetEditorDeleteDirectory;
import com.hypixel.hytale.protocol.packets.asseteditor.AssetEditorDiscardChanges;
import com.hypixel.hytale.protocol.packets.asseteditor.AssetEditorEnableAssetPack;
import com.hypixel.hytale.protocol.packets.asseteditor.AssetEditorExportAssetFinalize;
import com.hypixel.hytale.protocol.packets.asseteditor.AssetEditorExportAssetInitialize;
import com.hypixel.hytale.protocol.packets.asseteditor.AssetEditorExportAssetPart;
import com.hypixel.hytale.protocol.packets.asseteditor.AssetEditorExportAssets;
import com.hypixel.hytale.protocol.packets.asseteditor.AssetEditorExportComplete;
import com.hypixel.hytale.protocol.packets.asseteditor.AssetEditorExportDeleteAssets;
import com.hypixel.hytale.protocol.packets.asseteditor.AssetEditorFetchAsset;
import com.hypixel.hytale.protocol.packets.asseteditor.AssetEditorFetchAssetReply;
import com.hypixel.hytale.protocol.packets.asseteditor.AssetEditorFetchAutoCompleteData;
import com.hypixel.hytale.protocol.packets.asseteditor.AssetEditorFetchAutoCompleteDataReply;
import com.hypixel.hytale.protocol.packets.asseteditor.AssetEditorFetchJsonAssetWithParents;
import com.hypixel.hytale.protocol.packets.asseteditor.AssetEditorFetchJsonAssetWithParentsReply;
import com.hypixel.hytale.protocol.packets.asseteditor.AssetEditorFetchLastModifiedAssets;
import com.hypixel.hytale.protocol.packets.asseteditor.AssetEditorInitialize;
import com.hypixel.hytale.protocol.packets.asseteditor.AssetEditorJsonAssetUpdated;
import com.hypixel.hytale.protocol.packets.asseteditor.AssetEditorLastModifiedAssets;
import com.hypixel.hytale.protocol.packets.asseteditor.AssetEditorModifiedAssetsCount;
import com.hypixel.hytale.protocol.packets.asseteditor.AssetEditorPopupNotification;
import com.hypixel.hytale.protocol.packets.asseteditor.AssetEditorRebuildCaches;
import com.hypixel.hytale.protocol.packets.asseteditor.AssetEditorRedoChanges;
import com.hypixel.hytale.protocol.packets.asseteditor.AssetEditorRenameAsset;
import com.hypixel.hytale.protocol.packets.asseteditor.AssetEditorRenameDirectory;
import com.hypixel.hytale.protocol.packets.asseteditor.AssetEditorRequestChildrenList;
import com.hypixel.hytale.protocol.packets.asseteditor.AssetEditorRequestChildrenListReply;
import com.hypixel.hytale.protocol.packets.asseteditor.AssetEditorRequestDataset;
import com.hypixel.hytale.protocol.packets.asseteditor.AssetEditorRequestDatasetReply;
import com.hypixel.hytale.protocol.packets.asseteditor.AssetEditorSelectAsset;
import com.hypixel.hytale.protocol.packets.asseteditor.AssetEditorSetGameTime;
import com.hypixel.hytale.protocol.packets.asseteditor.AssetEditorSetupAssetTypes;
import com.hypixel.hytale.protocol.packets.asseteditor.AssetEditorSetupSchemas;
import com.hypixel.hytale.protocol.packets.asseteditor.AssetEditorSubscribeModifiedAssetsChanges;
import com.hypixel.hytale.protocol.packets.asseteditor.AssetEditorUndoChanges;
import com.hypixel.hytale.protocol.packets.asseteditor.AssetEditorUndoRedoReply;
import com.hypixel.hytale.protocol.packets.asseteditor.AssetEditorUpdateAsset;
import com.hypixel.hytale.protocol.packets.asseteditor.AssetEditorUpdateAssetPack;
import com.hypixel.hytale.protocol.packets.asseteditor.AssetEditorUpdateJsonAsset;
import com.hypixel.hytale.protocol.packets.asseteditor.AssetEditorUpdateModelPreview;
import com.hypixel.hytale.protocol.packets.asseteditor.AssetEditorUpdateSecondsPerGameDay;
import com.hypixel.hytale.protocol.packets.asseteditor.AssetEditorUpdateWeatherPreviewLock;
import com.hypixel.hytale.protocol.packets.asseteditor.FailureReply;
import com.hypixel.hytale.protocol.packets.asseteditor.SuccessReply;
import com.hypixel.hytale.protocol.packets.assets.TrackOrUpdateObjective;
import com.hypixel.hytale.protocol.packets.assets.UntrackObjective;
import com.hypixel.hytale.protocol.packets.assets.UpdateAmbienceFX;
import com.hypixel.hytale.protocol.packets.assets.UpdateAudioCategories;
import com.hypixel.hytale.protocol.packets.assets.UpdateBlockBreakingDecals;
import com.hypixel.hytale.protocol.packets.assets.UpdateBlockGroups;
import com.hypixel.hytale.protocol.packets.assets.UpdateBlockHitboxes;
import com.hypixel.hytale.protocol.packets.assets.UpdateBlockParticleSets;
import com.hypixel.hytale.protocol.packets.assets.UpdateBlockSets;
import com.hypixel.hytale.protocol.packets.assets.UpdateBlockSoundSets;
import com.hypixel.hytale.protocol.packets.assets.UpdateBlockTypes;
import com.hypixel.hytale.protocol.packets.assets.UpdateCameraShake;
import com.hypixel.hytale.protocol.packets.assets.UpdateEntityEffects;
import com.hypixel.hytale.protocol.packets.assets.UpdateEntityStatTypes;
import com.hypixel.hytale.protocol.packets.assets.UpdateEntityUIComponents;
import com.hypixel.hytale.protocol.packets.assets.UpdateEnvironments;
import com.hypixel.hytale.protocol.packets.assets.UpdateEqualizerEffects;
import com.hypixel.hytale.protocol.packets.assets.UpdateFieldcraftCategories;
import com.hypixel.hytale.protocol.packets.assets.UpdateFluidFX;
import com.hypixel.hytale.protocol.packets.assets.UpdateFluids;
import com.hypixel.hytale.protocol.packets.assets.UpdateHitboxCollisionConfig;
import com.hypixel.hytale.protocol.packets.assets.UpdateInteractions;
import com.hypixel.hytale.protocol.packets.assets.UpdateItemCategories;
import com.hypixel.hytale.protocol.packets.assets.UpdateItemPlayerAnimations;
import com.hypixel.hytale.protocol.packets.assets.UpdateItemQualities;
import com.hypixel.hytale.protocol.packets.assets.UpdateItemReticles;
import com.hypixel.hytale.protocol.packets.assets.UpdateItemSoundSets;
import com.hypixel.hytale.protocol.packets.assets.UpdateItems;
import com.hypixel.hytale.protocol.packets.assets.UpdateModelvfxs;
import com.hypixel.hytale.protocol.packets.assets.UpdateObjectiveTask;
import com.hypixel.hytale.protocol.packets.assets.UpdateParticleSpawners;
import com.hypixel.hytale.protocol.packets.assets.UpdateParticleSystems;
import com.hypixel.hytale.protocol.packets.assets.UpdateProjectileConfigs;
import com.hypixel.hytale.protocol.packets.assets.UpdateRecipes;
import com.hypixel.hytale.protocol.packets.assets.UpdateRepulsionConfig;
import com.hypixel.hytale.protocol.packets.assets.UpdateResourceTypes;
import com.hypixel.hytale.protocol.packets.assets.UpdateReverbEffects;
import com.hypixel.hytale.protocol.packets.assets.UpdateRootInteractions;
import com.hypixel.hytale.protocol.packets.assets.UpdateSoundEvents;
import com.hypixel.hytale.protocol.packets.assets.UpdateSoundSets;
import com.hypixel.hytale.protocol.packets.assets.UpdateTagPatterns;
import com.hypixel.hytale.protocol.packets.assets.UpdateTrails;
import com.hypixel.hytale.protocol.packets.assets.UpdateTranslations;
import com.hypixel.hytale.protocol.packets.assets.UpdateUnarmedInteractions;
import com.hypixel.hytale.protocol.packets.assets.UpdateViewBobbing;
import com.hypixel.hytale.protocol.packets.assets.UpdateWeathers;
import com.hypixel.hytale.protocol.packets.auth.AuthGrant;
import com.hypixel.hytale.protocol.packets.auth.AuthToken;
import com.hypixel.hytale.protocol.packets.auth.ClientReferral;
import com.hypixel.hytale.protocol.packets.auth.ConnectAccept;
import com.hypixel.hytale.protocol.packets.auth.PasswordAccepted;
import com.hypixel.hytale.protocol.packets.auth.PasswordRejected;
import com.hypixel.hytale.protocol.packets.auth.PasswordResponse;
import com.hypixel.hytale.protocol.packets.auth.ServerAuthToken;
import com.hypixel.hytale.protocol.packets.auth.Status;
import com.hypixel.hytale.protocol.packets.buildertools.BuilderToolArgUpdate;
import com.hypixel.hytale.protocol.packets.buildertools.BuilderToolEntityAction;
import com.hypixel.hytale.protocol.packets.buildertools.BuilderToolExtrudeAction;
import com.hypixel.hytale.protocol.packets.buildertools.BuilderToolGeneralAction;
import com.hypixel.hytale.protocol.packets.buildertools.BuilderToolHideAnchors;
import com.hypixel.hytale.protocol.packets.buildertools.BuilderToolLaserPointer;
import com.hypixel.hytale.protocol.packets.buildertools.BuilderToolLineAction;
import com.hypixel.hytale.protocol.packets.buildertools.BuilderToolOnUseInteraction;
import com.hypixel.hytale.protocol.packets.buildertools.BuilderToolPasteClipboard;
import com.hypixel.hytale.protocol.packets.buildertools.BuilderToolRotateClipboard;
import com.hypixel.hytale.protocol.packets.buildertools.BuilderToolSelectionToolAskForClipboard;
import com.hypixel.hytale.protocol.packets.buildertools.BuilderToolSelectionToolReplyWithClipboard;
import com.hypixel.hytale.protocol.packets.buildertools.BuilderToolSelectionTransform;
import com.hypixel.hytale.protocol.packets.buildertools.BuilderToolSelectionUpdate;
import com.hypixel.hytale.protocol.packets.buildertools.BuilderToolSetEntityLight;
import com.hypixel.hytale.protocol.packets.buildertools.BuilderToolSetEntityPickupEnabled;
import com.hypixel.hytale.protocol.packets.buildertools.BuilderToolSetEntityScale;
import com.hypixel.hytale.protocol.packets.buildertools.BuilderToolSetEntityTransform;
import com.hypixel.hytale.protocol.packets.buildertools.BuilderToolSetNPCDebug;
import com.hypixel.hytale.protocol.packets.buildertools.BuilderToolSetTransformationModeState;
import com.hypixel.hytale.protocol.packets.buildertools.BuilderToolShowAnchor;
import com.hypixel.hytale.protocol.packets.buildertools.BuilderToolStackArea;
import com.hypixel.hytale.protocol.packets.buildertools.BuilderToolsSetSoundSet;
import com.hypixel.hytale.protocol.packets.buildertools.PrefabUnselectPrefab;
import com.hypixel.hytale.protocol.packets.camera.CameraShakeEffect;
import com.hypixel.hytale.protocol.packets.camera.RequestFlyCameraMode;
import com.hypixel.hytale.protocol.packets.camera.SetFlyCameraMode;
import com.hypixel.hytale.protocol.packets.camera.SetServerCamera;
import com.hypixel.hytale.protocol.packets.connection.Connect;
import com.hypixel.hytale.protocol.packets.connection.Disconnect;
import com.hypixel.hytale.protocol.packets.connection.Ping;
import com.hypixel.hytale.protocol.packets.connection.Pong;
import com.hypixel.hytale.protocol.packets.entities.ApplyKnockback;
import com.hypixel.hytale.protocol.packets.entities.ChangeVelocity;
import com.hypixel.hytale.protocol.packets.entities.EntityUpdates;
import com.hypixel.hytale.protocol.packets.entities.MountMovement;
import com.hypixel.hytale.protocol.packets.entities.PlayAnimation;
import com.hypixel.hytale.protocol.packets.entities.SetEntitySeed;
import com.hypixel.hytale.protocol.packets.entities.SpawnModelParticles;
import com.hypixel.hytale.protocol.packets.interaction.CancelInteractionChain;
import com.hypixel.hytale.protocol.packets.interaction.DismountNPC;
import com.hypixel.hytale.protocol.packets.interaction.MountNPC;
import com.hypixel.hytale.protocol.packets.interaction.PlayInteractionFor;
import com.hypixel.hytale.protocol.packets.interaction.SyncInteractionChains;
import com.hypixel.hytale.protocol.packets.interface_.AddToServerPlayerList;
import com.hypixel.hytale.protocol.packets.interface_.ChatMessage;
import com.hypixel.hytale.protocol.packets.interface_.CustomHud;
import com.hypixel.hytale.protocol.packets.interface_.CustomPage;
import com.hypixel.hytale.protocol.packets.interface_.CustomPageEvent;
import com.hypixel.hytale.protocol.packets.interface_.EditorBlocksChange;
import com.hypixel.hytale.protocol.packets.interface_.HideEventTitle;
import com.hypixel.hytale.protocol.packets.interface_.KillFeedMessage;
import com.hypixel.hytale.protocol.packets.interface_.Notification;
import com.hypixel.hytale.protocol.packets.interface_.OpenChatWithCommand;
import com.hypixel.hytale.protocol.packets.interface_.RemoveFromServerPlayerList;
import com.hypixel.hytale.protocol.packets.interface_.ResetUserInterfaceState;
import com.hypixel.hytale.protocol.packets.interface_.ServerInfo;
import com.hypixel.hytale.protocol.packets.interface_.ServerMessage;
import com.hypixel.hytale.protocol.packets.interface_.SetPage;
import com.hypixel.hytale.protocol.packets.interface_.ShowEventTitle;
import com.hypixel.hytale.protocol.packets.interface_.UpdateKnownRecipes;
import com.hypixel.hytale.protocol.packets.interface_.UpdateLanguage;
import com.hypixel.hytale.protocol.packets.interface_.UpdatePortal;
import com.hypixel.hytale.protocol.packets.interface_.UpdateServerPlayerList;
import com.hypixel.hytale.protocol.packets.interface_.UpdateServerPlayerListPing;
import com.hypixel.hytale.protocol.packets.interface_.UpdateVisibleHudComponents;
import com.hypixel.hytale.protocol.packets.interface_.WorldSavingStatus;
import com.hypixel.hytale.protocol.packets.inventory.DropCreativeItem;
import com.hypixel.hytale.protocol.packets.inventory.DropItemStack;
import com.hypixel.hytale.protocol.packets.inventory.InventoryAction;
import com.hypixel.hytale.protocol.packets.inventory.MoveItemStack;
import com.hypixel.hytale.protocol.packets.inventory.SetActiveSlot;
import com.hypixel.hytale.protocol.packets.inventory.SetCreativeItem;
import com.hypixel.hytale.protocol.packets.inventory.SmartGiveCreativeItem;
import com.hypixel.hytale.protocol.packets.inventory.SmartMoveItemStack;
import com.hypixel.hytale.protocol.packets.inventory.SwitchHotbarBlockSet;
import com.hypixel.hytale.protocol.packets.inventory.UpdatePlayerInventory;
import com.hypixel.hytale.protocol.packets.machinima.RequestMachinimaActorModel;
import com.hypixel.hytale.protocol.packets.machinima.SetMachinimaActorModel;
import com.hypixel.hytale.protocol.packets.machinima.UpdateMachinimaScene;
import com.hypixel.hytale.protocol.packets.player.ClearDebugShapes;
import com.hypixel.hytale.protocol.packets.player.ClientMovement;
import com.hypixel.hytale.protocol.packets.player.ClientPlaceBlock;
import com.hypixel.hytale.protocol.packets.player.ClientReady;
import com.hypixel.hytale.protocol.packets.player.ClientTeleport;
import com.hypixel.hytale.protocol.packets.player.DamageInfo;
import com.hypixel.hytale.protocol.packets.player.DisplayDebug;
import com.hypixel.hytale.protocol.packets.player.JoinWorld;
import com.hypixel.hytale.protocol.packets.player.LoadHotbar;
import com.hypixel.hytale.protocol.packets.player.MouseInteraction;
import com.hypixel.hytale.protocol.packets.player.RemoveMapMarker;
import com.hypixel.hytale.protocol.packets.player.ReticleEvent;
import com.hypixel.hytale.protocol.packets.player.SaveHotbar;
import com.hypixel.hytale.protocol.packets.player.SetBlockPlacementOverride;
import com.hypixel.hytale.protocol.packets.player.SetClientId;
import com.hypixel.hytale.protocol.packets.player.SetGameMode;
import com.hypixel.hytale.protocol.packets.player.SetMovementStates;
import com.hypixel.hytale.protocol.packets.player.SyncPlayerPreferences;
import com.hypixel.hytale.protocol.packets.player.UpdateMemoriesFeatureStatus;
import com.hypixel.hytale.protocol.packets.player.UpdateMovementSettings;
import com.hypixel.hytale.protocol.packets.serveraccess.RequestServerAccess;
import com.hypixel.hytale.protocol.packets.serveraccess.SetServerAccess;
import com.hypixel.hytale.protocol.packets.serveraccess.UpdateServerAccess;
import com.hypixel.hytale.protocol.packets.setup.AssetFinalize;
import com.hypixel.hytale.protocol.packets.setup.AssetInitialize;
import com.hypixel.hytale.protocol.packets.setup.AssetPart;
import com.hypixel.hytale.protocol.packets.setup.PlayerOptions;
import com.hypixel.hytale.protocol.packets.setup.RemoveAssets;
import com.hypixel.hytale.protocol.packets.setup.RequestAssets;
import com.hypixel.hytale.protocol.packets.setup.RequestCommonAssetsRebuild;
import com.hypixel.hytale.protocol.packets.setup.ServerTags;
import com.hypixel.hytale.protocol.packets.setup.SetTimeDilation;
import com.hypixel.hytale.protocol.packets.setup.SetUpdateRate;
import com.hypixel.hytale.protocol.packets.setup.UpdateFeatures;
import com.hypixel.hytale.protocol.packets.setup.ViewRadius;
import com.hypixel.hytale.protocol.packets.setup.WorldLoadFinished;
import com.hypixel.hytale.protocol.packets.setup.WorldLoadProgress;
import com.hypixel.hytale.protocol.packets.setup.WorldSettings;
import com.hypixel.hytale.protocol.packets.window.ClientOpenWindow;
import com.hypixel.hytale.protocol.packets.window.CloseWindow;
import com.hypixel.hytale.protocol.packets.window.OpenWindow;
import com.hypixel.hytale.protocol.packets.window.SendWindowAction;
import com.hypixel.hytale.protocol.packets.window.UpdateWindow;
import com.hypixel.hytale.protocol.packets.world.ClearEditorTimeOverride;
import com.hypixel.hytale.protocol.packets.world.PlaySoundEvent2D;
import com.hypixel.hytale.protocol.packets.world.PlaySoundEvent3D;
import com.hypixel.hytale.protocol.packets.world.PlaySoundEventEntity;
import com.hypixel.hytale.protocol.packets.world.ServerSetBlock;
import com.hypixel.hytale.protocol.packets.world.ServerSetBlocks;
import com.hypixel.hytale.protocol.packets.world.ServerSetFluid;
import com.hypixel.hytale.protocol.packets.world.ServerSetFluids;
import com.hypixel.hytale.protocol.packets.world.ServerSetPaused;
import com.hypixel.hytale.protocol.packets.world.SetChunk;
import com.hypixel.hytale.protocol.packets.world.SetChunkEnvironments;
import com.hypixel.hytale.protocol.packets.world.SetChunkHeightmap;
import com.hypixel.hytale.protocol.packets.world.SetChunkTintmap;
import com.hypixel.hytale.protocol.packets.world.SetFluids;
import com.hypixel.hytale.protocol.packets.world.SetPaused;
import com.hypixel.hytale.protocol.packets.world.SpawnBlockParticleSystem;
import com.hypixel.hytale.protocol.packets.world.SpawnParticleSystem;
import com.hypixel.hytale.protocol.packets.world.UnloadChunk;
import com.hypixel.hytale.protocol.packets.world.UpdateBlockDamage;
import com.hypixel.hytale.protocol.packets.world.UpdateEditorTimeOverride;
import com.hypixel.hytale.protocol.packets.world.UpdateEditorWeatherOverride;
import com.hypixel.hytale.protocol.packets.world.UpdateEnvironmentMusic;
import com.hypixel.hytale.protocol.packets.world.UpdatePostFxSettings;
import com.hypixel.hytale.protocol.packets.world.UpdateSleepState;
import com.hypixel.hytale.protocol.packets.world.UpdateSunSettings;
import com.hypixel.hytale.protocol.packets.world.UpdateTime;
import com.hypixel.hytale.protocol.packets.world.UpdateTimeSettings;
import com.hypixel.hytale.protocol.packets.world.UpdateWeather;
import com.hypixel.hytale.protocol.packets.worldmap.ClearWorldMap;
import com.hypixel.hytale.protocol.packets.worldmap.TeleportToWorldMapMarker;
import com.hypixel.hytale.protocol.packets.worldmap.TeleportToWorldMapPosition;
import com.hypixel.hytale.protocol.packets.worldmap.UpdateWorldMap;
import com.hypixel.hytale.protocol.packets.worldmap.UpdateWorldMapSettings;
import com.hypixel.hytale.protocol.packets.worldmap.UpdateWorldMapVisible;
import io.netty.buffer.ByteBuf;
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;
import java.util.function.BiFunction;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;

public final class PacketRegistry {
    private static final Map<Integer, PacketInfo> BY_ID = new HashMap<Integer, PacketInfo>();
    private static final Map<Integer, PacketInfo> BY_ID_UNMODIFIABLE = Collections.unmodifiableMap(BY_ID);
    private static final Map<Class<? extends Packet>, Integer> BY_TYPE = new HashMap<Class<? extends Packet>, Integer>();

    private PacketRegistry() {
    }

    private static void register(int id, String name, Class<? extends Packet> type, int fixedBlockSize, int maxSize, boolean compressed, BiFunction<ByteBuf, Integer, ValidationResult> validate, BiFunction<ByteBuf, Integer, Packet> deserialize) {
        PacketInfo existing = BY_ID.get(id);
        if (existing != null) {
            throw new IllegalStateException("Duplicate packet ID " + id + ": '" + name + "' conflicts with '" + existing.name() + "'");
        }
        PacketInfo info = new PacketInfo(id, name, type, fixedBlockSize, maxSize, compressed, validate, deserialize);
        BY_ID.put(id, info);
        BY_TYPE.put(type, id);
    }

    @Nullable
    public static PacketInfo getById(int id) {
        return BY_ID.get(id);
    }

    @Nullable
    public static Integer getId(Class<? extends Packet> type) {
        return BY_TYPE.get(type);
    }

    @Nonnull
    public static Map<Integer, PacketInfo> all() {
        return BY_ID_UNMODIFIABLE;
    }

    static {
        PacketRegistry.register(0, "Connect", Connect.class, 82, 38161, false, Connect::validateStructure, Connect::deserialize);
        PacketRegistry.register(1, "Disconnect", Disconnect.class, 2, 16384007, false, Disconnect::validateStructure, Disconnect::deserialize);
        PacketRegistry.register(2, "Ping", Ping.class, 29, 29, false, Ping::validateStructure, Ping::deserialize);
        PacketRegistry.register(3, "Pong", Pong.class, 20, 20, false, Pong::validateStructure, Pong::deserialize);
        PacketRegistry.register(10, "Status", Status.class, 9, 2587, false, Status::validateStructure, Status::deserialize);
        PacketRegistry.register(11, "AuthGrant", AuthGrant.class, 1, 49171, false, AuthGrant::validateStructure, AuthGrant::deserialize);
        PacketRegistry.register(12, "AuthToken", AuthToken.class, 1, 49171, false, AuthToken::validateStructure, AuthToken::deserialize);
        PacketRegistry.register(13, "ServerAuthToken", ServerAuthToken.class, 1, 32851, false, ServerAuthToken::validateStructure, ServerAuthToken::deserialize);
        PacketRegistry.register(14, "ConnectAccept", ConnectAccept.class, 1, 70, false, ConnectAccept::validateStructure, ConnectAccept::deserialize);
        PacketRegistry.register(15, "PasswordResponse", PasswordResponse.class, 1, 70, false, PasswordResponse::validateStructure, PasswordResponse::deserialize);
        PacketRegistry.register(16, "PasswordAccepted", PasswordAccepted.class, 0, 0, false, PasswordAccepted::validateStructure, PasswordAccepted::deserialize);
        PacketRegistry.register(17, "PasswordRejected", PasswordRejected.class, 5, 74, false, PasswordRejected::validateStructure, PasswordRejected::deserialize);
        PacketRegistry.register(18, "ClientReferral", ClientReferral.class, 1, 5141, false, ClientReferral::validateStructure, ClientReferral::deserialize);
        PacketRegistry.register(20, "WorldSettings", WorldSettings.class, 5, 0x64000000, true, WorldSettings::validateStructure, WorldSettings::deserialize);
        PacketRegistry.register(21, "WorldLoadProgress", WorldLoadProgress.class, 9, 16384014, false, WorldLoadProgress::validateStructure, WorldLoadProgress::deserialize);
        PacketRegistry.register(22, "WorldLoadFinished", WorldLoadFinished.class, 0, 0, false, WorldLoadFinished::validateStructure, WorldLoadFinished::deserialize);
        PacketRegistry.register(23, "RequestAssets", RequestAssets.class, 1, 0x64000000, true, RequestAssets::validateStructure, RequestAssets::deserialize);
        PacketRegistry.register(24, "AssetInitialize", AssetInitialize.class, 4, 2121, false, AssetInitialize::validateStructure, AssetInitialize::deserialize);
        PacketRegistry.register(25, "AssetPart", AssetPart.class, 1, 4096006, true, AssetPart::validateStructure, AssetPart::deserialize);
        PacketRegistry.register(26, "AssetFinalize", AssetFinalize.class, 0, 0, false, AssetFinalize::validateStructure, AssetFinalize::deserialize);
        PacketRegistry.register(27, "RemoveAssets", RemoveAssets.class, 1, 0x64000000, false, RemoveAssets::validateStructure, RemoveAssets::deserialize);
        PacketRegistry.register(28, "RequestCommonAssetsRebuild", RequestCommonAssetsRebuild.class, 0, 0, false, RequestCommonAssetsRebuild::validateStructure, RequestCommonAssetsRebuild::deserialize);
        PacketRegistry.register(29, "SetUpdateRate", SetUpdateRate.class, 4, 4, false, SetUpdateRate::validateStructure, SetUpdateRate::deserialize);
        PacketRegistry.register(30, "SetTimeDilation", SetTimeDilation.class, 4, 4, false, SetTimeDilation::validateStructure, SetTimeDilation::deserialize);
        PacketRegistry.register(31, "UpdateFeatures", UpdateFeatures.class, 1, 8192006, false, UpdateFeatures::validateStructure, UpdateFeatures::deserialize);
        PacketRegistry.register(32, "ViewRadius", ViewRadius.class, 4, 4, false, ViewRadius::validateStructure, ViewRadius::deserialize);
        PacketRegistry.register(33, "PlayerOptions", PlayerOptions.class, 1, 327680184, false, PlayerOptions::validateStructure, PlayerOptions::deserialize);
        PacketRegistry.register(34, "ServerTags", ServerTags.class, 1, 0x64000000, false, ServerTags::validateStructure, ServerTags::deserialize);
        PacketRegistry.register(40, "UpdateBlockTypes", UpdateBlockTypes.class, 10, 0x64000000, true, UpdateBlockTypes::validateStructure, UpdateBlockTypes::deserialize);
        PacketRegistry.register(41, "UpdateBlockHitboxes", UpdateBlockHitboxes.class, 6, 0x64000000, true, UpdateBlockHitboxes::validateStructure, UpdateBlockHitboxes::deserialize);
        PacketRegistry.register(42, "UpdateBlockSoundSets", UpdateBlockSoundSets.class, 6, 0x64000000, true, UpdateBlockSoundSets::validateStructure, UpdateBlockSoundSets::deserialize);
        PacketRegistry.register(43, "UpdateItemSoundSets", UpdateItemSoundSets.class, 6, 0x64000000, true, UpdateItemSoundSets::validateStructure, UpdateItemSoundSets::deserialize);
        PacketRegistry.register(44, "UpdateBlockParticleSets", UpdateBlockParticleSets.class, 2, 0x64000000, true, UpdateBlockParticleSets::validateStructure, UpdateBlockParticleSets::deserialize);
        PacketRegistry.register(45, "UpdateBlockBreakingDecals", UpdateBlockBreakingDecals.class, 2, 0x64000000, true, UpdateBlockBreakingDecals::validateStructure, UpdateBlockBreakingDecals::deserialize);
        PacketRegistry.register(46, "UpdateBlockSets", UpdateBlockSets.class, 2, 0x64000000, true, UpdateBlockSets::validateStructure, UpdateBlockSets::deserialize);
        PacketRegistry.register(47, "UpdateWeathers", UpdateWeathers.class, 6, 0x64000000, true, UpdateWeathers::validateStructure, UpdateWeathers::deserialize);
        PacketRegistry.register(48, "UpdateTrails", UpdateTrails.class, 2, 0x64000000, true, UpdateTrails::validateStructure, UpdateTrails::deserialize);
        PacketRegistry.register(49, "UpdateParticleSystems", UpdateParticleSystems.class, 2, 0x64000000, true, UpdateParticleSystems::validateStructure, UpdateParticleSystems::deserialize);
        PacketRegistry.register(50, "UpdateParticleSpawners", UpdateParticleSpawners.class, 2, 0x64000000, true, UpdateParticleSpawners::validateStructure, UpdateParticleSpawners::deserialize);
        PacketRegistry.register(51, "UpdateEntityEffects", UpdateEntityEffects.class, 6, 0x64000000, true, UpdateEntityEffects::validateStructure, UpdateEntityEffects::deserialize);
        PacketRegistry.register(52, "UpdateItemPlayerAnimations", UpdateItemPlayerAnimations.class, 2, 0x64000000, true, UpdateItemPlayerAnimations::validateStructure, UpdateItemPlayerAnimations::deserialize);
        PacketRegistry.register(53, "UpdateModelvfxs", UpdateModelvfxs.class, 6, 0x64000000, true, UpdateModelvfxs::validateStructure, UpdateModelvfxs::deserialize);
        PacketRegistry.register(54, "UpdateItems", UpdateItems.class, 4, 0x64000000, true, UpdateItems::validateStructure, UpdateItems::deserialize);
        PacketRegistry.register(55, "UpdateItemQualities", UpdateItemQualities.class, 6, 0x64000000, true, UpdateItemQualities::validateStructure, UpdateItemQualities::deserialize);
        PacketRegistry.register(56, "UpdateItemCategories", UpdateItemCategories.class, 2, 0x64000000, true, UpdateItemCategories::validateStructure, UpdateItemCategories::deserialize);
        PacketRegistry.register(57, "UpdateItemReticles", UpdateItemReticles.class, 6, 0x64000000, true, UpdateItemReticles::validateStructure, UpdateItemReticles::deserialize);
        PacketRegistry.register(58, "UpdateFieldcraftCategories", UpdateFieldcraftCategories.class, 2, 0x64000000, true, UpdateFieldcraftCategories::validateStructure, UpdateFieldcraftCategories::deserialize);
        PacketRegistry.register(59, "UpdateResourceTypes", UpdateResourceTypes.class, 2, 0x64000000, true, UpdateResourceTypes::validateStructure, UpdateResourceTypes::deserialize);
        PacketRegistry.register(60, "UpdateRecipes", UpdateRecipes.class, 2, 0x64000000, true, UpdateRecipes::validateStructure, UpdateRecipes::deserialize);
        PacketRegistry.register(61, "UpdateEnvironments", UpdateEnvironments.class, 7, 0x64000000, true, UpdateEnvironments::validateStructure, UpdateEnvironments::deserialize);
        PacketRegistry.register(62, "UpdateAmbienceFX", UpdateAmbienceFX.class, 6, 0x64000000, true, UpdateAmbienceFX::validateStructure, UpdateAmbienceFX::deserialize);
        PacketRegistry.register(63, "UpdateFluidFX", UpdateFluidFX.class, 6, 0x64000000, true, UpdateFluidFX::validateStructure, UpdateFluidFX::deserialize);
        PacketRegistry.register(64, "UpdateTranslations", UpdateTranslations.class, 2, 0x64000000, true, UpdateTranslations::validateStructure, UpdateTranslations::deserialize);
        PacketRegistry.register(65, "UpdateSoundEvents", UpdateSoundEvents.class, 6, 0x64000000, true, UpdateSoundEvents::validateStructure, UpdateSoundEvents::deserialize);
        PacketRegistry.register(66, "UpdateInteractions", UpdateInteractions.class, 6, 0x64000000, true, UpdateInteractions::validateStructure, UpdateInteractions::deserialize);
        PacketRegistry.register(67, "UpdateRootInteractions", UpdateRootInteractions.class, 6, 0x64000000, true, UpdateRootInteractions::validateStructure, UpdateRootInteractions::deserialize);
        PacketRegistry.register(68, "UpdateUnarmedInteractions", UpdateUnarmedInteractions.class, 2, 20480007, true, UpdateUnarmedInteractions::validateStructure, UpdateUnarmedInteractions::deserialize);
        PacketRegistry.register(69, "TrackOrUpdateObjective", TrackOrUpdateObjective.class, 1, 0x64000000, false, TrackOrUpdateObjective::validateStructure, TrackOrUpdateObjective::deserialize);
        PacketRegistry.register(70, "UntrackObjective", UntrackObjective.class, 16, 16, false, UntrackObjective::validateStructure, UntrackObjective::deserialize);
        PacketRegistry.register(71, "UpdateObjectiveTask", UpdateObjectiveTask.class, 21, 16384035, false, UpdateObjectiveTask::validateStructure, UpdateObjectiveTask::deserialize);
        PacketRegistry.register(72, "UpdateEntityStatTypes", UpdateEntityStatTypes.class, 6, 0x64000000, true, UpdateEntityStatTypes::validateStructure, UpdateEntityStatTypes::deserialize);
        PacketRegistry.register(73, "UpdateEntityUIComponents", UpdateEntityUIComponents.class, 6, 0x64000000, true, UpdateEntityUIComponents::validateStructure, UpdateEntityUIComponents::deserialize);
        PacketRegistry.register(74, "UpdateHitboxCollisionConfig", UpdateHitboxCollisionConfig.class, 6, 36864011, true, UpdateHitboxCollisionConfig::validateStructure, UpdateHitboxCollisionConfig::deserialize);
        PacketRegistry.register(75, "UpdateRepulsionConfig", UpdateRepulsionConfig.class, 6, 65536011, true, UpdateRepulsionConfig::validateStructure, UpdateRepulsionConfig::deserialize);
        PacketRegistry.register(76, "UpdateViewBobbing", UpdateViewBobbing.class, 2, 0x64000000, true, UpdateViewBobbing::validateStructure, UpdateViewBobbing::deserialize);
        PacketRegistry.register(77, "UpdateCameraShake", UpdateCameraShake.class, 2, 0x64000000, true, UpdateCameraShake::validateStructure, UpdateCameraShake::deserialize);
        PacketRegistry.register(78, "UpdateBlockGroups", UpdateBlockGroups.class, 2, 0x64000000, true, UpdateBlockGroups::validateStructure, UpdateBlockGroups::deserialize);
        PacketRegistry.register(79, "UpdateSoundSets", UpdateSoundSets.class, 6, 0x64000000, true, UpdateSoundSets::validateStructure, UpdateSoundSets::deserialize);
        PacketRegistry.register(80, "UpdateAudioCategories", UpdateAudioCategories.class, 6, 0x64000000, true, UpdateAudioCategories::validateStructure, UpdateAudioCategories::deserialize);
        PacketRegistry.register(81, "UpdateReverbEffects", UpdateReverbEffects.class, 6, 0x64000000, true, UpdateReverbEffects::validateStructure, UpdateReverbEffects::deserialize);
        PacketRegistry.register(82, "UpdateEqualizerEffects", UpdateEqualizerEffects.class, 6, 0x64000000, true, UpdateEqualizerEffects::validateStructure, UpdateEqualizerEffects::deserialize);
        PacketRegistry.register(83, "UpdateFluids", UpdateFluids.class, 6, 0x64000000, true, UpdateFluids::validateStructure, UpdateFluids::deserialize);
        PacketRegistry.register(84, "UpdateTagPatterns", UpdateTagPatterns.class, 6, 0x64000000, true, UpdateTagPatterns::validateStructure, UpdateTagPatterns::deserialize);
        PacketRegistry.register(85, "UpdateProjectileConfigs", UpdateProjectileConfigs.class, 2, 0x64000000, true, UpdateProjectileConfigs::validateStructure, UpdateProjectileConfigs::deserialize);
        PacketRegistry.register(100, "SetClientId", SetClientId.class, 4, 4, false, SetClientId::validateStructure, SetClientId::deserialize);
        PacketRegistry.register(101, "SetGameMode", SetGameMode.class, 1, 1, false, SetGameMode::validateStructure, SetGameMode::deserialize);
        PacketRegistry.register(102, "SetMovementStates", SetMovementStates.class, 2, 2, false, SetMovementStates::validateStructure, SetMovementStates::deserialize);
        PacketRegistry.register(103, "SetBlockPlacementOverride", SetBlockPlacementOverride.class, 1, 1, false, SetBlockPlacementOverride::validateStructure, SetBlockPlacementOverride::deserialize);
        PacketRegistry.register(104, "JoinWorld", JoinWorld.class, 18, 18, false, JoinWorld::validateStructure, JoinWorld::deserialize);
        PacketRegistry.register(105, "ClientReady", ClientReady.class, 2, 2, false, ClientReady::validateStructure, ClientReady::deserialize);
        PacketRegistry.register(106, "LoadHotbar", LoadHotbar.class, 1, 1, false, LoadHotbar::validateStructure, LoadHotbar::deserialize);
        PacketRegistry.register(107, "SaveHotbar", SaveHotbar.class, 1, 1, false, SaveHotbar::validateStructure, SaveHotbar::deserialize);
        PacketRegistry.register(108, "ClientMovement", ClientMovement.class, 153, 153, false, ClientMovement::validateStructure, ClientMovement::deserialize);
        PacketRegistry.register(109, "ClientTeleport", ClientTeleport.class, 52, 52, false, ClientTeleport::validateStructure, ClientTeleport::deserialize);
        PacketRegistry.register(110, "UpdateMovementSettings", UpdateMovementSettings.class, 252, 252, false, UpdateMovementSettings::validateStructure, UpdateMovementSettings::deserialize);
        PacketRegistry.register(111, "MouseInteraction", MouseInteraction.class, 44, 20480071, false, MouseInteraction::validateStructure, MouseInteraction::deserialize);
        PacketRegistry.register(112, "DamageInfo", DamageInfo.class, 29, 32768048, false, DamageInfo::validateStructure, DamageInfo::deserialize);
        PacketRegistry.register(113, "ReticleEvent", ReticleEvent.class, 4, 4, false, ReticleEvent::validateStructure, ReticleEvent::deserialize);
        PacketRegistry.register(114, "DisplayDebug", DisplayDebug.class, 19, 32768037, false, DisplayDebug::validateStructure, DisplayDebug::deserialize);
        PacketRegistry.register(115, "ClearDebugShapes", ClearDebugShapes.class, 0, 0, false, ClearDebugShapes::validateStructure, ClearDebugShapes::deserialize);
        PacketRegistry.register(116, "SyncPlayerPreferences", SyncPlayerPreferences.class, 8, 8, false, SyncPlayerPreferences::validateStructure, SyncPlayerPreferences::deserialize);
        PacketRegistry.register(117, "ClientPlaceBlock", ClientPlaceBlock.class, 20, 20, false, ClientPlaceBlock::validateStructure, ClientPlaceBlock::deserialize);
        PacketRegistry.register(118, "UpdateMemoriesFeatureStatus", UpdateMemoriesFeatureStatus.class, 1, 1, false, UpdateMemoriesFeatureStatus::validateStructure, UpdateMemoriesFeatureStatus::deserialize);
        PacketRegistry.register(119, "RemoveMapMarker", RemoveMapMarker.class, 1, 16384006, false, RemoveMapMarker::validateStructure, RemoveMapMarker::deserialize);
        PacketRegistry.register(131, "SetChunk", SetChunk.class, 13, 12288040, true, SetChunk::validateStructure, SetChunk::deserialize);
        PacketRegistry.register(132, "SetChunkHeightmap", SetChunkHeightmap.class, 9, 4096014, true, SetChunkHeightmap::validateStructure, SetChunkHeightmap::deserialize);
        PacketRegistry.register(133, "SetChunkTintmap", SetChunkTintmap.class, 9, 4096014, true, SetChunkTintmap::validateStructure, SetChunkTintmap::deserialize);
        PacketRegistry.register(134, "SetChunkEnvironments", SetChunkEnvironments.class, 9, 4096014, true, SetChunkEnvironments::validateStructure, SetChunkEnvironments::deserialize);
        PacketRegistry.register(135, "UnloadChunk", UnloadChunk.class, 8, 8, false, UnloadChunk::validateStructure, UnloadChunk::deserialize);
        PacketRegistry.register(136, "SetFluids", SetFluids.class, 13, 4096018, true, SetFluids::validateStructure, SetFluids::deserialize);
        PacketRegistry.register(140, "ServerSetBlock", ServerSetBlock.class, 19, 19, false, ServerSetBlock::validateStructure, ServerSetBlock::deserialize);
        PacketRegistry.register(141, "ServerSetBlocks", ServerSetBlocks.class, 12, 36864017, false, ServerSetBlocks::validateStructure, ServerSetBlocks::deserialize);
        PacketRegistry.register(142, "ServerSetFluid", ServerSetFluid.class, 17, 17, false, ServerSetFluid::validateStructure, ServerSetFluid::deserialize);
        PacketRegistry.register(143, "ServerSetFluids", ServerSetFluids.class, 12, 28672017, false, ServerSetFluids::validateStructure, ServerSetFluids::deserialize);
        PacketRegistry.register(144, "UpdateBlockDamage", UpdateBlockDamage.class, 21, 21, false, UpdateBlockDamage::validateStructure, UpdateBlockDamage::deserialize);
        PacketRegistry.register(145, "UpdateTimeSettings", UpdateTimeSettings.class, 10, 10, false, UpdateTimeSettings::validateStructure, UpdateTimeSettings::deserialize);
        PacketRegistry.register(146, "UpdateTime", UpdateTime.class, 13, 13, false, UpdateTime::validateStructure, UpdateTime::deserialize);
        PacketRegistry.register(147, "UpdateEditorTimeOverride", UpdateEditorTimeOverride.class, 14, 14, false, UpdateEditorTimeOverride::validateStructure, UpdateEditorTimeOverride::deserialize);
        PacketRegistry.register(148, "ClearEditorTimeOverride", ClearEditorTimeOverride.class, 0, 0, false, ClearEditorTimeOverride::validateStructure, ClearEditorTimeOverride::deserialize);
        PacketRegistry.register(149, "UpdateWeather", UpdateWeather.class, 8, 8, false, UpdateWeather::validateStructure, UpdateWeather::deserialize);
        PacketRegistry.register(150, "UpdateEditorWeatherOverride", UpdateEditorWeatherOverride.class, 4, 4, false, UpdateEditorWeatherOverride::validateStructure, UpdateEditorWeatherOverride::deserialize);
        PacketRegistry.register(151, "UpdateEnvironmentMusic", UpdateEnvironmentMusic.class, 4, 4, false, UpdateEnvironmentMusic::validateStructure, UpdateEnvironmentMusic::deserialize);
        PacketRegistry.register(152, "SpawnParticleSystem", SpawnParticleSystem.class, 44, 16384049, false, SpawnParticleSystem::validateStructure, SpawnParticleSystem::deserialize);
        PacketRegistry.register(153, "SpawnBlockParticleSystem", SpawnBlockParticleSystem.class, 30, 30, false, SpawnBlockParticleSystem::validateStructure, SpawnBlockParticleSystem::deserialize);
        PacketRegistry.register(154, "PlaySoundEvent2D", PlaySoundEvent2D.class, 13, 13, false, PlaySoundEvent2D::validateStructure, PlaySoundEvent2D::deserialize);
        PacketRegistry.register(155, "PlaySoundEvent3D", PlaySoundEvent3D.class, 38, 38, false, PlaySoundEvent3D::validateStructure, PlaySoundEvent3D::deserialize);
        PacketRegistry.register(156, "PlaySoundEventEntity", PlaySoundEventEntity.class, 16, 16, false, PlaySoundEventEntity::validateStructure, PlaySoundEventEntity::deserialize);
        PacketRegistry.register(157, "UpdateSleepState", UpdateSleepState.class, 36, 65536050, false, UpdateSleepState::validateStructure, UpdateSleepState::deserialize);
        PacketRegistry.register(158, "SetPaused", SetPaused.class, 1, 1, false, SetPaused::validateStructure, SetPaused::deserialize);
        PacketRegistry.register(159, "ServerSetPaused", ServerSetPaused.class, 1, 1, false, ServerSetPaused::validateStructure, ServerSetPaused::deserialize);
        PacketRegistry.register(160, "SetEntitySeed", SetEntitySeed.class, 4, 4, false, SetEntitySeed::validateStructure, SetEntitySeed::deserialize);
        PacketRegistry.register(161, "EntityUpdates", EntityUpdates.class, 1, 0x64000000, true, EntityUpdates::validateStructure, EntityUpdates::deserialize);
        PacketRegistry.register(162, "PlayAnimation", PlayAnimation.class, 6, 32768024, false, PlayAnimation::validateStructure, PlayAnimation::deserialize);
        PacketRegistry.register(163, "ChangeVelocity", ChangeVelocity.class, 35, 35, false, ChangeVelocity::validateStructure, ChangeVelocity::deserialize);
        PacketRegistry.register(164, "ApplyKnockback", ApplyKnockback.class, 38, 38, false, ApplyKnockback::validateStructure, ApplyKnockback::deserialize);
        PacketRegistry.register(165, "SpawnModelParticles", SpawnModelParticles.class, 5, 0x64000000, false, SpawnModelParticles::validateStructure, SpawnModelParticles::deserialize);
        PacketRegistry.register(166, "MountMovement", MountMovement.class, 59, 59, false, MountMovement::validateStructure, MountMovement::deserialize);
        PacketRegistry.register(170, "UpdatePlayerInventory", UpdatePlayerInventory.class, 2, 0x64000000, true, UpdatePlayerInventory::validateStructure, UpdatePlayerInventory::deserialize);
        PacketRegistry.register(171, "SetCreativeItem", SetCreativeItem.class, 9, 16384019, false, SetCreativeItem::validateStructure, SetCreativeItem::deserialize);
        PacketRegistry.register(172, "DropCreativeItem", DropCreativeItem.class, 0, 0xFA000A, false, DropCreativeItem::validateStructure, DropCreativeItem::deserialize);
        PacketRegistry.register(173, "SmartGiveCreativeItem", SmartGiveCreativeItem.class, 1, 16384011, false, SmartGiveCreativeItem::validateStructure, SmartGiveCreativeItem::deserialize);
        PacketRegistry.register(174, "DropItemStack", DropItemStack.class, 12, 12, false, DropItemStack::validateStructure, DropItemStack::deserialize);
        PacketRegistry.register(175, "MoveItemStack", MoveItemStack.class, 20, 20, false, MoveItemStack::validateStructure, MoveItemStack::deserialize);
        PacketRegistry.register(176, "SmartMoveItemStack", SmartMoveItemStack.class, 13, 13, false, SmartMoveItemStack::validateStructure, SmartMoveItemStack::deserialize);
        PacketRegistry.register(177, "SetActiveSlot", SetActiveSlot.class, 8, 8, false, SetActiveSlot::validateStructure, SetActiveSlot::deserialize);
        PacketRegistry.register(178, "SwitchHotbarBlockSet", SwitchHotbarBlockSet.class, 1, 16384006, false, SwitchHotbarBlockSet::validateStructure, SwitchHotbarBlockSet::deserialize);
        PacketRegistry.register(179, "InventoryAction", InventoryAction.class, 6, 6, false, InventoryAction::validateStructure, InventoryAction::deserialize);
        PacketRegistry.register(200, "OpenWindow", OpenWindow.class, 6, 0x64000000, true, OpenWindow::validateStructure, OpenWindow::deserialize);
        PacketRegistry.register(201, "UpdateWindow", UpdateWindow.class, 5, 0x64000000, true, UpdateWindow::validateStructure, UpdateWindow::deserialize);
        PacketRegistry.register(202, "CloseWindow", CloseWindow.class, 4, 4, false, CloseWindow::validateStructure, CloseWindow::deserialize);
        PacketRegistry.register(203, "SendWindowAction", SendWindowAction.class, 4, 32768027, false, SendWindowAction::validateStructure, SendWindowAction::deserialize);
        PacketRegistry.register(204, "ClientOpenWindow", ClientOpenWindow.class, 1, 1, false, ClientOpenWindow::validateStructure, ClientOpenWindow::deserialize);
        PacketRegistry.register(210, "ServerMessage", ServerMessage.class, 2, 0x64000000, false, ServerMessage::validateStructure, ServerMessage::deserialize);
        PacketRegistry.register(211, "ChatMessage", ChatMessage.class, 1, 16384006, false, ChatMessage::validateStructure, ChatMessage::deserialize);
        PacketRegistry.register(212, "Notification", Notification.class, 2, 0x64000000, false, Notification::validateStructure, Notification::deserialize);
        PacketRegistry.register(213, "KillFeedMessage", KillFeedMessage.class, 1, 0x64000000, false, KillFeedMessage::validateStructure, KillFeedMessage::deserialize);
        PacketRegistry.register(214, "ShowEventTitle", ShowEventTitle.class, 14, 0x64000000, false, ShowEventTitle::validateStructure, ShowEventTitle::deserialize);
        PacketRegistry.register(215, "HideEventTitle", HideEventTitle.class, 4, 4, false, HideEventTitle::validateStructure, HideEventTitle::deserialize);
        PacketRegistry.register(216, "SetPage", SetPage.class, 2, 2, false, SetPage::validateStructure, SetPage::deserialize);
        PacketRegistry.register(217, "CustomHud", CustomHud.class, 2, 0x64000000, true, CustomHud::validateStructure, CustomHud::deserialize);
        PacketRegistry.register(218, "CustomPage", CustomPage.class, 4, 0x64000000, true, CustomPage::validateStructure, CustomPage::deserialize);
        PacketRegistry.register(219, "CustomPageEvent", CustomPageEvent.class, 2, 16384007, false, CustomPageEvent::validateStructure, CustomPageEvent::deserialize);
        PacketRegistry.register(222, "EditorBlocksChange", EditorBlocksChange.class, 30, 139264048, true, EditorBlocksChange::validateStructure, EditorBlocksChange::deserialize);
        PacketRegistry.register(223, "ServerInfo", ServerInfo.class, 5, 32768023, false, ServerInfo::validateStructure, ServerInfo::deserialize);
        PacketRegistry.register(224, "AddToServerPlayerList", AddToServerPlayerList.class, 1, 0x64000000, false, AddToServerPlayerList::validateStructure, AddToServerPlayerList::deserialize);
        PacketRegistry.register(225, "RemoveFromServerPlayerList", RemoveFromServerPlayerList.class, 1, 65536006, false, RemoveFromServerPlayerList::validateStructure, RemoveFromServerPlayerList::deserialize);
        PacketRegistry.register(226, "UpdateServerPlayerList", UpdateServerPlayerList.class, 1, 131072006, false, UpdateServerPlayerList::validateStructure, UpdateServerPlayerList::deserialize);
        PacketRegistry.register(227, "UpdateServerPlayerListPing", UpdateServerPlayerListPing.class, 1, 81920006, false, UpdateServerPlayerListPing::validateStructure, UpdateServerPlayerListPing::deserialize);
        PacketRegistry.register(228, "UpdateKnownRecipes", UpdateKnownRecipes.class, 1, 0x64000000, false, UpdateKnownRecipes::validateStructure, UpdateKnownRecipes::deserialize);
        PacketRegistry.register(229, "UpdatePortal", UpdatePortal.class, 6, 16384020, false, UpdatePortal::validateStructure, UpdatePortal::deserialize);
        PacketRegistry.register(230, "UpdateVisibleHudComponents", UpdateVisibleHudComponents.class, 1, 4096006, false, UpdateVisibleHudComponents::validateStructure, UpdateVisibleHudComponents::deserialize);
        PacketRegistry.register(231, "ResetUserInterfaceState", ResetUserInterfaceState.class, 0, 0, false, ResetUserInterfaceState::validateStructure, ResetUserInterfaceState::deserialize);
        PacketRegistry.register(232, "UpdateLanguage", UpdateLanguage.class, 1, 16384006, false, UpdateLanguage::validateStructure, UpdateLanguage::deserialize);
        PacketRegistry.register(233, "WorldSavingStatus", WorldSavingStatus.class, 1, 1, false, WorldSavingStatus::validateStructure, WorldSavingStatus::deserialize);
        PacketRegistry.register(234, "OpenChatWithCommand", OpenChatWithCommand.class, 1, 16384006, false, OpenChatWithCommand::validateStructure, OpenChatWithCommand::deserialize);
        PacketRegistry.register(240, "UpdateWorldMapSettings", UpdateWorldMapSettings.class, 16, 0x64000000, false, UpdateWorldMapSettings::validateStructure, UpdateWorldMapSettings::deserialize);
        PacketRegistry.register(241, "UpdateWorldMap", UpdateWorldMap.class, 1, 0x64000000, true, UpdateWorldMap::validateStructure, UpdateWorldMap::deserialize);
        PacketRegistry.register(242, "ClearWorldMap", ClearWorldMap.class, 0, 0, false, ClearWorldMap::validateStructure, ClearWorldMap::deserialize);
        PacketRegistry.register(243, "UpdateWorldMapVisible", UpdateWorldMapVisible.class, 1, 1, false, UpdateWorldMapVisible::validateStructure, UpdateWorldMapVisible::deserialize);
        PacketRegistry.register(244, "TeleportToWorldMapMarker", TeleportToWorldMapMarker.class, 1, 16384006, false, TeleportToWorldMapMarker::validateStructure, TeleportToWorldMapMarker::deserialize);
        PacketRegistry.register(245, "TeleportToWorldMapPosition", TeleportToWorldMapPosition.class, 8, 8, false, TeleportToWorldMapPosition::validateStructure, TeleportToWorldMapPosition::deserialize);
        PacketRegistry.register(250, "RequestServerAccess", RequestServerAccess.class, 3, 3, false, RequestServerAccess::validateStructure, RequestServerAccess::deserialize);
        PacketRegistry.register(251, "UpdateServerAccess", UpdateServerAccess.class, 2, 0x64000000, false, UpdateServerAccess::validateStructure, UpdateServerAccess::deserialize);
        PacketRegistry.register(252, "SetServerAccess", SetServerAccess.class, 2, 16384007, false, SetServerAccess::validateStructure, SetServerAccess::deserialize);
        PacketRegistry.register(260, "RequestMachinimaActorModel", RequestMachinimaActorModel.class, 1, 49152028, false, RequestMachinimaActorModel::validateStructure, RequestMachinimaActorModel::deserialize);
        PacketRegistry.register(261, "SetMachinimaActorModel", SetMachinimaActorModel.class, 1, 0x64000000, false, SetMachinimaActorModel::validateStructure, SetMachinimaActorModel::deserialize);
        PacketRegistry.register(262, "UpdateMachinimaScene", UpdateMachinimaScene.class, 6, 36864033, true, UpdateMachinimaScene::validateStructure, UpdateMachinimaScene::deserialize);
        PacketRegistry.register(280, "SetServerCamera", SetServerCamera.class, 157, 157, false, SetServerCamera::validateStructure, SetServerCamera::deserialize);
        PacketRegistry.register(281, "CameraShakeEffect", CameraShakeEffect.class, 9, 9, false, CameraShakeEffect::validateStructure, CameraShakeEffect::deserialize);
        PacketRegistry.register(282, "RequestFlyCameraMode", RequestFlyCameraMode.class, 1, 1, false, RequestFlyCameraMode::validateStructure, RequestFlyCameraMode::deserialize);
        PacketRegistry.register(283, "SetFlyCameraMode", SetFlyCameraMode.class, 1, 1, false, SetFlyCameraMode::validateStructure, SetFlyCameraMode::deserialize);
        PacketRegistry.register(290, "SyncInteractionChains", SyncInteractionChains.class, 0, 0x64000000, false, SyncInteractionChains::validateStructure, SyncInteractionChains::deserialize);
        PacketRegistry.register(291, "CancelInteractionChain", CancelInteractionChain.class, 5, 1038, false, CancelInteractionChain::validateStructure, CancelInteractionChain::deserialize);
        PacketRegistry.register(292, "PlayInteractionFor", PlayInteractionFor.class, 19, 16385065, false, PlayInteractionFor::validateStructure, PlayInteractionFor::deserialize);
        PacketRegistry.register(293, "MountNPC", MountNPC.class, 16, 16, false, MountNPC::validateStructure, MountNPC::deserialize);
        PacketRegistry.register(294, "DismountNPC", DismountNPC.class, 0, 0, false, DismountNPC::validateStructure, DismountNPC::deserialize);
        PacketRegistry.register(300, "FailureReply", FailureReply.class, 5, 0x64000000, false, FailureReply::validateStructure, FailureReply::deserialize);
        PacketRegistry.register(301, "SuccessReply", SuccessReply.class, 5, 0x64000000, false, SuccessReply::validateStructure, SuccessReply::deserialize);
        PacketRegistry.register(302, "AssetEditorInitialize", AssetEditorInitialize.class, 0, 0, false, AssetEditorInitialize::validateStructure, AssetEditorInitialize::deserialize);
        PacketRegistry.register(303, "AssetEditorAuthorization", AssetEditorAuthorization.class, 1, 1, false, AssetEditorAuthorization::validateStructure, AssetEditorAuthorization::deserialize);
        PacketRegistry.register(304, "AssetEditorCapabilities", AssetEditorCapabilities.class, 5, 5, false, AssetEditorCapabilities::validateStructure, AssetEditorCapabilities::deserialize);
        PacketRegistry.register(305, "AssetEditorSetupSchemas", AssetEditorSetupSchemas.class, 1, 0x64000000, true, AssetEditorSetupSchemas::validateStructure, AssetEditorSetupSchemas::deserialize);
        PacketRegistry.register(306, "AssetEditorSetupAssetTypes", AssetEditorSetupAssetTypes.class, 1, 0x64000000, false, AssetEditorSetupAssetTypes::validateStructure, AssetEditorSetupAssetTypes::deserialize);
        PacketRegistry.register(307, "AssetEditorCreateDirectory", AssetEditorCreateDirectory.class, 5, 32768024, false, AssetEditorCreateDirectory::validateStructure, AssetEditorCreateDirectory::deserialize);
        PacketRegistry.register(308, "AssetEditorDeleteDirectory", AssetEditorDeleteDirectory.class, 5, 32768024, false, AssetEditorDeleteDirectory::validateStructure, AssetEditorDeleteDirectory::deserialize);
        PacketRegistry.register(309, "AssetEditorRenameDirectory", AssetEditorRenameDirectory.class, 5, 65536051, false, AssetEditorRenameDirectory::validateStructure, AssetEditorRenameDirectory::deserialize);
        PacketRegistry.register(310, "AssetEditorFetchAsset", AssetEditorFetchAsset.class, 6, 32768025, false, AssetEditorFetchAsset::validateStructure, AssetEditorFetchAsset::deserialize);
        PacketRegistry.register(311, "AssetEditorFetchJsonAssetWithParents", AssetEditorFetchJsonAssetWithParents.class, 6, 32768025, false, AssetEditorFetchJsonAssetWithParents::validateStructure, AssetEditorFetchJsonAssetWithParents::deserialize);
        PacketRegistry.register(312, "AssetEditorFetchAssetReply", AssetEditorFetchAssetReply.class, 5, 4096010, false, AssetEditorFetchAssetReply::validateStructure, AssetEditorFetchAssetReply::deserialize);
        PacketRegistry.register(313, "AssetEditorFetchJsonAssetWithParentsReply", AssetEditorFetchJsonAssetWithParentsReply.class, 5, 0x64000000, true, AssetEditorFetchJsonAssetWithParentsReply::validateStructure, AssetEditorFetchJsonAssetWithParentsReply::deserialize);
        PacketRegistry.register(314, "AssetEditorAssetPackSetup", AssetEditorAssetPackSetup.class, 1, 0x64000000, false, AssetEditorAssetPackSetup::validateStructure, AssetEditorAssetPackSetup::deserialize);
        PacketRegistry.register(315, "AssetEditorUpdateAssetPack", AssetEditorUpdateAssetPack.class, 1, 0x64000000, false, AssetEditorUpdateAssetPack::validateStructure, AssetEditorUpdateAssetPack::deserialize);
        PacketRegistry.register(316, "AssetEditorCreateAssetPack", AssetEditorCreateAssetPack.class, 5, 0x64000000, false, AssetEditorCreateAssetPack::validateStructure, AssetEditorCreateAssetPack::deserialize);
        PacketRegistry.register(317, "AssetEditorDeleteAssetPack", AssetEditorDeleteAssetPack.class, 1, 16384006, false, AssetEditorDeleteAssetPack::validateStructure, AssetEditorDeleteAssetPack::deserialize);
        PacketRegistry.register(318, "AssetEditorEnableAssetPack", AssetEditorEnableAssetPack.class, 2, 16384007, false, AssetEditorEnableAssetPack::validateStructure, AssetEditorEnableAssetPack::deserialize);
        PacketRegistry.register(319, "AssetEditorAssetListSetup", AssetEditorAssetListSetup.class, 4, 0x64000000, true, AssetEditorAssetListSetup::validateStructure, AssetEditorAssetListSetup::deserialize);
        PacketRegistry.register(320, "AssetEditorAssetListUpdate", AssetEditorAssetListUpdate.class, 1, 0x64000000, true, AssetEditorAssetListUpdate::validateStructure, AssetEditorAssetListUpdate::deserialize);
        PacketRegistry.register(321, "AssetEditorRequestChildrenList", AssetEditorRequestChildrenList.class, 1, 32768020, false, AssetEditorRequestChildrenList::validateStructure, AssetEditorRequestChildrenList::deserialize);
        PacketRegistry.register(322, "AssetEditorRequestChildrenListReply", AssetEditorRequestChildrenListReply.class, 1, 0x64000000, false, AssetEditorRequestChildrenListReply::validateStructure, AssetEditorRequestChildrenListReply::deserialize);
        PacketRegistry.register(323, "AssetEditorUpdateJsonAsset", AssetEditorUpdateJsonAsset.class, 9, 0x64000000, true, AssetEditorUpdateJsonAsset::validateStructure, AssetEditorUpdateJsonAsset::deserialize);
        PacketRegistry.register(324, "AssetEditorUpdateAsset", AssetEditorUpdateAsset.class, 9, 53248050, false, AssetEditorUpdateAsset::validateStructure, AssetEditorUpdateAsset::deserialize);
        PacketRegistry.register(325, "AssetEditorJsonAssetUpdated", AssetEditorJsonAssetUpdated.class, 1, 0x64000000, false, AssetEditorJsonAssetUpdated::validateStructure, AssetEditorJsonAssetUpdated::deserialize);
        PacketRegistry.register(326, "AssetEditorAssetUpdated", AssetEditorAssetUpdated.class, 1, 36864033, false, AssetEditorAssetUpdated::validateStructure, AssetEditorAssetUpdated::deserialize);
        PacketRegistry.register(327, "AssetEditorCreateAsset", AssetEditorCreateAsset.class, 10, 53248051, false, AssetEditorCreateAsset::validateStructure, AssetEditorCreateAsset::deserialize);
        PacketRegistry.register(328, "AssetEditorRenameAsset", AssetEditorRenameAsset.class, 5, 65536051, false, AssetEditorRenameAsset::validateStructure, AssetEditorRenameAsset::deserialize);
        PacketRegistry.register(329, "AssetEditorDeleteAsset", AssetEditorDeleteAsset.class, 5, 32768024, false, AssetEditorDeleteAsset::validateStructure, AssetEditorDeleteAsset::deserialize);
        PacketRegistry.register(330, "AssetEditorDiscardChanges", AssetEditorDiscardChanges.class, 1, 0x64000000, false, AssetEditorDiscardChanges::validateStructure, AssetEditorDiscardChanges::deserialize);
        PacketRegistry.register(331, "AssetEditorFetchAutoCompleteData", AssetEditorFetchAutoCompleteData.class, 5, 32768023, false, AssetEditorFetchAutoCompleteData::validateStructure, AssetEditorFetchAutoCompleteData::deserialize);
        PacketRegistry.register(332, "AssetEditorFetchAutoCompleteDataReply", AssetEditorFetchAutoCompleteDataReply.class, 5, 0x64000000, false, AssetEditorFetchAutoCompleteDataReply::validateStructure, AssetEditorFetchAutoCompleteDataReply::deserialize);
        PacketRegistry.register(333, "AssetEditorRequestDataset", AssetEditorRequestDataset.class, 1, 16384006, false, AssetEditorRequestDataset::validateStructure, AssetEditorRequestDataset::deserialize);
        PacketRegistry.register(334, "AssetEditorRequestDatasetReply", AssetEditorRequestDatasetReply.class, 1, 0x64000000, false, AssetEditorRequestDatasetReply::validateStructure, AssetEditorRequestDatasetReply::deserialize);
        PacketRegistry.register(335, "AssetEditorActivateButton", AssetEditorActivateButton.class, 1, 16384006, false, AssetEditorActivateButton::validateStructure, AssetEditorActivateButton::deserialize);
        PacketRegistry.register(336, "AssetEditorSelectAsset", AssetEditorSelectAsset.class, 1, 32768020, false, AssetEditorSelectAsset::validateStructure, AssetEditorSelectAsset::deserialize);
        PacketRegistry.register(337, "AssetEditorPopupNotification", AssetEditorPopupNotification.class, 2, 0x64000000, false, AssetEditorPopupNotification::validateStructure, AssetEditorPopupNotification::deserialize);
        PacketRegistry.register(338, "AssetEditorFetchLastModifiedAssets", AssetEditorFetchLastModifiedAssets.class, 0, 0, false, AssetEditorFetchLastModifiedAssets::validateStructure, AssetEditorFetchLastModifiedAssets::deserialize);
        PacketRegistry.register(339, "AssetEditorLastModifiedAssets", AssetEditorLastModifiedAssets.class, 1, 0x64000000, false, AssetEditorLastModifiedAssets::validateStructure, AssetEditorLastModifiedAssets::deserialize);
        PacketRegistry.register(340, "AssetEditorModifiedAssetsCount", AssetEditorModifiedAssetsCount.class, 4, 4, false, AssetEditorModifiedAssetsCount::validateStructure, AssetEditorModifiedAssetsCount::deserialize);
        PacketRegistry.register(341, "AssetEditorSubscribeModifiedAssetsChanges", AssetEditorSubscribeModifiedAssetsChanges.class, 1, 1, false, AssetEditorSubscribeModifiedAssetsChanges::validateStructure, AssetEditorSubscribeModifiedAssetsChanges::deserialize);
        PacketRegistry.register(342, "AssetEditorExportAssets", AssetEditorExportAssets.class, 1, 0x64000000, false, AssetEditorExportAssets::validateStructure, AssetEditorExportAssets::deserialize);
        PacketRegistry.register(343, "AssetEditorExportAssetInitialize", AssetEditorExportAssetInitialize.class, 6, 81920066, false, AssetEditorExportAssetInitialize::validateStructure, AssetEditorExportAssetInitialize::deserialize);
        PacketRegistry.register(344, "AssetEditorExportAssetPart", AssetEditorExportAssetPart.class, 1, 4096006, true, AssetEditorExportAssetPart::validateStructure, AssetEditorExportAssetPart::deserialize);
        PacketRegistry.register(345, "AssetEditorExportAssetFinalize", AssetEditorExportAssetFinalize.class, 0, 0, false, AssetEditorExportAssetFinalize::validateStructure, AssetEditorExportAssetFinalize::deserialize);
        PacketRegistry.register(346, "AssetEditorExportDeleteAssets", AssetEditorExportDeleteAssets.class, 1, 0x64000000, false, AssetEditorExportDeleteAssets::validateStructure, AssetEditorExportDeleteAssets::deserialize);
        PacketRegistry.register(347, "AssetEditorExportComplete", AssetEditorExportComplete.class, 1, 0x64000000, false, AssetEditorExportComplete::validateStructure, AssetEditorExportComplete::deserialize);
        PacketRegistry.register(348, "AssetEditorRebuildCaches", AssetEditorRebuildCaches.class, 5, 5, false, AssetEditorRebuildCaches::validateStructure, AssetEditorRebuildCaches::deserialize);
        PacketRegistry.register(349, "AssetEditorUndoChanges", AssetEditorUndoChanges.class, 5, 32768024, false, AssetEditorUndoChanges::validateStructure, AssetEditorUndoChanges::deserialize);
        PacketRegistry.register(350, "AssetEditorRedoChanges", AssetEditorRedoChanges.class, 5, 32768024, false, AssetEditorRedoChanges::validateStructure, AssetEditorRedoChanges::deserialize);
        PacketRegistry.register(351, "AssetEditorUndoRedoReply", AssetEditorUndoRedoReply.class, 5, 0x64000000, false, AssetEditorUndoRedoReply::validateStructure, AssetEditorUndoRedoReply::deserialize);
        PacketRegistry.register(352, "AssetEditorSetGameTime", AssetEditorSetGameTime.class, 14, 14, false, AssetEditorSetGameTime::validateStructure, AssetEditorSetGameTime::deserialize);
        PacketRegistry.register(353, "AssetEditorUpdateSecondsPerGameDay", AssetEditorUpdateSecondsPerGameDay.class, 8, 8, false, AssetEditorUpdateSecondsPerGameDay::validateStructure, AssetEditorUpdateSecondsPerGameDay::deserialize);
        PacketRegistry.register(354, "AssetEditorUpdateWeatherPreviewLock", AssetEditorUpdateWeatherPreviewLock.class, 1, 1, false, AssetEditorUpdateWeatherPreviewLock::validateStructure, AssetEditorUpdateWeatherPreviewLock::deserialize);
        PacketRegistry.register(355, "AssetEditorUpdateModelPreview", AssetEditorUpdateModelPreview.class, 30, 0x64000000, false, AssetEditorUpdateModelPreview::validateStructure, AssetEditorUpdateModelPreview::deserialize);
        PacketRegistry.register(360, "UpdateSunSettings", UpdateSunSettings.class, 8, 8, false, UpdateSunSettings::validateStructure, UpdateSunSettings::deserialize);
        PacketRegistry.register(361, "UpdatePostFxSettings", UpdatePostFxSettings.class, 20, 20, false, UpdatePostFxSettings::validateStructure, UpdatePostFxSettings::deserialize);
        PacketRegistry.register(400, "BuilderToolArgUpdate", BuilderToolArgUpdate.class, 14, 32768032, false, BuilderToolArgUpdate::validateStructure, BuilderToolArgUpdate::deserialize);
        PacketRegistry.register(401, "BuilderToolEntityAction", BuilderToolEntityAction.class, 5, 5, false, BuilderToolEntityAction::validateStructure, BuilderToolEntityAction::deserialize);
        PacketRegistry.register(402, "BuilderToolSetEntityTransform", BuilderToolSetEntityTransform.class, 54, 54, false, BuilderToolSetEntityTransform::validateStructure, BuilderToolSetEntityTransform::deserialize);
        PacketRegistry.register(403, "BuilderToolExtrudeAction", BuilderToolExtrudeAction.class, 24, 24, false, BuilderToolExtrudeAction::validateStructure, BuilderToolExtrudeAction::deserialize);
        PacketRegistry.register(404, "BuilderToolStackArea", BuilderToolStackArea.class, 41, 41, false, BuilderToolStackArea::validateStructure, BuilderToolStackArea::deserialize);
        PacketRegistry.register(405, "BuilderToolSelectionTransform", BuilderToolSelectionTransform.class, 52, 16384057, false, BuilderToolSelectionTransform::validateStructure, BuilderToolSelectionTransform::deserialize);
        PacketRegistry.register(406, "BuilderToolRotateClipboard", BuilderToolRotateClipboard.class, 5, 5, false, BuilderToolRotateClipboard::validateStructure, BuilderToolRotateClipboard::deserialize);
        PacketRegistry.register(407, "BuilderToolPasteClipboard", BuilderToolPasteClipboard.class, 12, 12, false, BuilderToolPasteClipboard::validateStructure, BuilderToolPasteClipboard::deserialize);
        PacketRegistry.register(408, "BuilderToolSetTransformationModeState", BuilderToolSetTransformationModeState.class, 1, 1, false, BuilderToolSetTransformationModeState::validateStructure, BuilderToolSetTransformationModeState::deserialize);
        PacketRegistry.register(409, "BuilderToolSelectionUpdate", BuilderToolSelectionUpdate.class, 24, 24, false, BuilderToolSelectionUpdate::validateStructure, BuilderToolSelectionUpdate::deserialize);
        PacketRegistry.register(410, "BuilderToolSelectionToolAskForClipboard", BuilderToolSelectionToolAskForClipboard.class, 0, 0, false, BuilderToolSelectionToolAskForClipboard::validateStructure, BuilderToolSelectionToolAskForClipboard::deserialize);
        PacketRegistry.register(411, "BuilderToolSelectionToolReplyWithClipboard", BuilderToolSelectionToolReplyWithClipboard.class, 1, 139264019, true, BuilderToolSelectionToolReplyWithClipboard::validateStructure, BuilderToolSelectionToolReplyWithClipboard::deserialize);
        PacketRegistry.register(412, "BuilderToolGeneralAction", BuilderToolGeneralAction.class, 1, 1, false, BuilderToolGeneralAction::validateStructure, BuilderToolGeneralAction::deserialize);
        PacketRegistry.register(413, "BuilderToolOnUseInteraction", BuilderToolOnUseInteraction.class, 57, 57, false, BuilderToolOnUseInteraction::validateStructure, BuilderToolOnUseInteraction::deserialize);
        PacketRegistry.register(414, "BuilderToolLineAction", BuilderToolLineAction.class, 24, 24, false, BuilderToolLineAction::validateStructure, BuilderToolLineAction::deserialize);
        PacketRegistry.register(415, "BuilderToolShowAnchor", BuilderToolShowAnchor.class, 12, 12, false, BuilderToolShowAnchor::validateStructure, BuilderToolShowAnchor::deserialize);
        PacketRegistry.register(416, "BuilderToolHideAnchors", BuilderToolHideAnchors.class, 0, 0, false, BuilderToolHideAnchors::validateStructure, BuilderToolHideAnchors::deserialize);
        PacketRegistry.register(417, "PrefabUnselectPrefab", PrefabUnselectPrefab.class, 0, 0, false, PrefabUnselectPrefab::validateStructure, PrefabUnselectPrefab::deserialize);
        PacketRegistry.register(418, "BuilderToolsSetSoundSet", BuilderToolsSetSoundSet.class, 4, 4, false, BuilderToolsSetSoundSet::validateStructure, BuilderToolsSetSoundSet::deserialize);
        PacketRegistry.register(419, "BuilderToolLaserPointer", BuilderToolLaserPointer.class, 36, 36, false, BuilderToolLaserPointer::validateStructure, BuilderToolLaserPointer::deserialize);
        PacketRegistry.register(420, "BuilderToolSetEntityScale", BuilderToolSetEntityScale.class, 8, 8, false, BuilderToolSetEntityScale::validateStructure, BuilderToolSetEntityScale::deserialize);
        PacketRegistry.register(421, "BuilderToolSetEntityPickupEnabled", BuilderToolSetEntityPickupEnabled.class, 5, 5, false, BuilderToolSetEntityPickupEnabled::validateStructure, BuilderToolSetEntityPickupEnabled::deserialize);
        PacketRegistry.register(422, "BuilderToolSetEntityLight", BuilderToolSetEntityLight.class, 9, 9, false, BuilderToolSetEntityLight::validateStructure, BuilderToolSetEntityLight::deserialize);
        PacketRegistry.register(423, "BuilderToolSetNPCDebug", BuilderToolSetNPCDebug.class, 5, 5, false, BuilderToolSetNPCDebug::validateStructure, BuilderToolSetNPCDebug::deserialize);
    }

    public record PacketInfo(int id, @Nonnull String name, @Nonnull Class<? extends Packet> type, int fixedBlockSize, int maxSize, boolean compressed, @Nonnull BiFunction<ByteBuf, Integer, ValidationResult> validate, @Nonnull BiFunction<ByteBuf, Integer, Packet> deserialize) {
    }
}

